name: Sync adPEASS with PEASS-ng & Create Pull Request

on:
  push

permissions:
  pull-requests: write

jobs:

  sync-adPEAS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'toxicphreAK/PEASS-ng'
    - uses: nxtlvlsoftware/git-subtree-action@1.1
      with:
        repo: 'toxicphreAK/adPEAS'
        path: 'adPEAS'
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        force: true
